### ISSUE TITLE
support image show center?

### ISSUE THREAD

**Issue by songxiaoliang** [enzomanuelmangano/react-native-qrcode-skia#1]
support image show center?

**Comment by enzomanuelmangano** [comment]
Hey @songxiaoliang, sorry for my late reply! 
You can now place a custom logo with the [latest release](https://github.com/enzomanuelmangano/react-native-qrcode-skia/releases/tag/v0.3.0). 

Have a try at [qrcode.reactiive.io](https://qrcode.reactiive.io) to quickly generate a new qrcode :)
