### ISSUE TITLE
Not working on snack.expo

### ISSUE THREAD

**Issue by Angelk90** [enzomanuelmangano/react-native-qrcode-skia#2]
Hi @enzomanuelmangano, tested it on snack.expo.dev, but it doesn't work.

Link: https://snack.expo.dev/dARuRAO-AjF1Or1oXzOJg

```
Cannot read properties of undefined (reading 'Path')
TypeError: Cannot read properties of undefined (reading 'Path')
    at r.value (@shopify/react-native.skia
    at eval (react-native-qrcode.skia
    at eval (react-native-qrcode.skia
```

**Comment by enzomanuelmangano** [comment]
Just tried with your snack expo dev and it seems that it's working fine. 
Please check that you're using the latest version: `"react-native-qrcode-skia": "0.3.0"`
<img width="1728" alt="Screenshot 2024-09-19 alle 16 32 51" src="https://github.com/user-attachments/assets/37ae3787-c954-4fb4-aff1-8a188f5242bb">

Closing the issue, feel free to reopen it if you're still getting the issue
